# Inherits
inherit_specs build/specs/common.sh

inherit_specs build/specs/dbengine.sh
inherit_specs build/specs/httpd.sh

inherit_specs build/specs/lms.sh
inherit_specs build/specs/sso.sh
inherit_specs build/specs/cms.sh
inherit_specs build/specs/its.sh
inherit_specs build/specs/scmr.sh
inherit_specs build/specs/ci.sh

# Overrides
MCI_SITE_NAME=miing.org
MCI_SITE_CONFIG=sites/miing/miing.org/config
MCI_SITE_THEMES=sites/miing/miing.org/themes

MCI_DBENGINE_MYSQL_ROOTPW=xbml610XBML
MCI_DBENGINE_PGSQL_ROOTPW=xbml610XBML

MCI_LMS=sentry
MCI_LMS_SENTRY_SITE=logs.miing.org
MCI_LMS_SENTRY_PGSQL_DBPW=mise610MISE

MCI_SSO=migo
MCI_SSO_MIGO_SITE=login.miing.org

MCI_CMS=(cmscustom mediawiki)
MCI_CMS_CUSTOM_SITE=miing.org
MCI_CMS_MEDIAWIKI_SITE=wiki.miing.org
MCI_CMS_MEDIAWIKI_DBENGINE_DBPW=mimw610MIMW
MCI_CMS_MEDIAWIKI_SITE_AUTH=openid
MCI_CMS_MEDIAWIKI_SITE_NAME=Miing
MCI_CMS_MEDIAWIKI_SITE_ADMIN=miing
MCI_CMS_MEDIAWIKI_SITE_ADMIN_PASSWORD=sami610SAMI
MCI_CMS_MEDIAWIKI_SITE_LOGO=miing-logo.png
MCI_CMS_MEDIAWIKI_SITE_FAVICON=favicon.ico

MCI_ITS=bugzilla
MCI_ITS_BUGZILLA_SITE=bugs.miing.org
MCI_ITS_BUGZILLA_DBENGINE_DBPW=mibz610MIBZ
MCI_ITS_BUGZILLA_SITE_AUTH=openid
MCI_ITS_BUGZILLA_SITE_ADMIN_EMAIL=samuel.miing@gmail.com
MCI_ITS_BUGZILLA_SITE_ADMIN_PASSWORD=sami610SAMI
MCI_ITS_BUGZILLA_SITE_ADMIN_REALNAME="Samuel Mi"
MCI_ITS_BUGZILLA_SITE_SMTP_SERVER=localhost
MCI_ITS_BUGZILLA_SITE_NO_PAUSE=0

MCI_SCMR=gerrit
MCI_SCMR_GERRIT_SITE=review.miing.org
MCI_SCMR_GERRIT_DBENGINE_DBPW=mige610MIGE
MCI_SCMR_GERRIT_SITE_AUTH=openidsso
MCI_SCMR_GERRIT_SITE_OPENIDSSO_URL=https://login.miing.org
MCI_SCMR_GERRIT_SSHGIT_CONFIG=ssh.config
MCI_SCMR_GERRIT_SSHGIT_USER=miing
MCI_SCMR_GERRIT_SSHGIT_EMAIL=samuel.miing@gmail.com
MCI_SCMR_GERRIT_SSHGIT_EDITOR=vim
MCI_SCMR_GERRIT_SITE_THEME=sapphire

MCI_CI=jenkins
MCI_CI_JENKINS_SITE=jenkins.miing.org
MCI_CI_JENKINS_SITE_AUTH=openid
MCI_CI_JENKINS_SITE_ADMIN_USER=miing
MCI_CI_JENKINS_SITE_ADMIN_PASSWORD=sami610SAMI
